module.exports = [
  {
    before:"./assets/images/before_1.png",
    after:"./assets/images/after_1.png"
  },
  {
    before:"./assets/images/before_2.png",
    after:"./assets/images/after_2.png"
  },
  {
    before:"./assets/images/before_3.png",
    after:"./assets/images/after_3.png"
  },
  {
    before:"./assets/images/before_4.png",
    after:"./assets/images/after_4.png"
  },
  {
    before:"./assets/images/before_5.png",
    after:"./assets/images/after_5.png"
  },
  {
    before:"./assets/images/before_6.png",
    after:"./assets/images/after_6.png"
  },
  {
    before:"./assets/images/before_7.png",
    after:"./assets/images/after_7.png"
  },
  {
    before:"./assets/images/before_8.png",
    after:"./assets/images/after_8.png"
  }
]
